version: '3.7'

services:
  app:
    container_name: flexvpn_api
    image: flexvpn_api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - app_db

  app_db:
    container_name: flexvpn_db
    hostname: flexvpn_db
    image: library/postgres:14.1
    environment:
      - POSTGRES_USER=flex
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=app
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: flexvpn_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - 6379:6379

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: flexvpn_main